"use client";
import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Interview = { id: string; candidate_name: string; title: string; room_name: string; status: string };

export default function LiveInterviewPage() {
  const { id } = useParams<{ id: string }>(); const video = useRef<HTMLVideoElement>(null); const [interview, setInterview] = useState<Interview | null>(null); const [stream, setStream] = useState<MediaStream | null>(null); const [sharing, setSharing] = useState(false); const [message, setMessage] = useState("Waiting room");
  useEffect(() => { fetch(`${API}/api/v1/interviews/${id}`, { headers: { Authorization: `Bearer ${localStorage.getItem("authentiq_session") ?? ""}` } }).then((r) => r.json()).then(setInterview); return () => stream?.getTracks().forEach((track) => track.stop()); }, [id, stream]);
  async function startCamera() { const media = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); setStream(media); if (video.current) video.current.srcObject = media; setMessage("Camera and microphone ready"); }
  async function shareScreen() { const display = await navigator.mediaDevices.getDisplayMedia({ video: true }); if (video.current) video.current.srcObject = display; setSharing(true); display.getVideoTracks()[0].addEventListener("ended", () => setSharing(false)); }
  async function signal(type: string, severity = "informational") { await fetch(`${API}/api/v1/interviews/${id}/events`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("authentiq_session") ?? ""}` }, body: JSON.stringify({ type, timestamp: new Date().toISOString(), severity, metadata: { source: "interview-room" } }) }); setMessage(`Recorded signal: ${type}`); }
  return <main className="simple-page live-room"><a className="back-link" href="/dashboard">← Back to dashboard</a><p className="eyebrow red">LIVE INTERVIEW / INTEGRITY ROOM</p><h1>{interview?.title ?? "Interview room"}</h1><p className="page-intro">{interview?.candidate_name ?? "Loading candidate…"} · {message}</p><section className="live-grid"><div className="video-panel"><video ref={video} autoPlay muted playsInline /><div className="room-controls"><button className="primary-button" onClick={startCamera}>{stream ? "Camera ready" : "Enable camera + mic"}</button><button className="secondary-button" onClick={shareScreen}>{sharing ? "Screen sharing" : "Share screen"}</button></div></div><aside className="integrity-panel"><p className="eyebrow">PRIVATE INTERVIEWER CONSOLE</p><h2>Integrity signals</h2><p>Signals are evidence for human review, not automatic decisions.</p><button className="signal-button" onClick={() => signal("candidate_verified")}>✓ Candidate verified</button><button className="signal-button" onClick={() => signal("liveness_check")}>◉ Liveness check</button><button className="signal-button warning" onClick={() => signal("off_screen_attention", "warning")}>! Mark attention signal</button><button className="signal-button critical" onClick={() => signal("manual_review_requested", "critical")}>↗ Request human review</button></aside></section></main>;
}
