"use client";
import { FormEvent, useState } from "react";

const checks = ["Identity verification", "Continuous face presence", "Liveness challenges", "Gaze and head analysis", "Browser activity", "Screen-sharing monitoring", "Deepfake analysis", "Audio analysis"];

export default function NewInterviewPage() {
  const [enabled, setEnabled] = useState<Record<string, boolean>>(Object.fromEntries(checks.map((check) => [check, true])));
  const [created, setCreated] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setError(""); const data = new FormData(event.currentTarget); const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"; const payload = { candidate_name: data.get("candidate") as string, candidate_email: data.get("email") as string, candidate_reference: (data.get("reference") as string) || null, title: data.get("title") as string, description: (data.get("description") as string) || null, scheduled_at: `${data.get("date")}T${data.get("time")}:00`, duration_minutes: Number.parseInt((data.get("duration") as string).match(/\d+/)?.[0] ?? "45", 10), monitoring: Object.fromEntries(checks.map((check) => [check.toLowerCase().replaceAll(" ", "_"), enabled[check]])) }; try { const response = await fetch(`${apiUrl}/api/v1/interviews`, { method: "POST", headers: { "Content-Type": "application/json", "X-Organization-Id": "demo-organization" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error("The API could not create this interview."); setCreated(true); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Something went wrong while creating the interview."); } finally { setSubmitting(false); } }
  return <main className="form-shell"><header className="form-header"><a className="back-link" href="/">← Back to overview</a><p className="eyebrow red">NEW SESSION / STEP 01</p><h1>Create an interview</h1><p>Set up a secure session and choose the integrity signals that should be observed.</p></header><form className="interview-form" onSubmit={submit}><FormSection index="01" label="CANDIDATE DETAILS"><div className="field-grid"><Field label="Candidate full name" name="candidate" placeholder="e.g. Ayesha Rahman" required /><Field label="Candidate email" name="email" type="email" placeholder="candidate@email.com" required /><Field label="Candidate reference (optional)" name="reference" placeholder="e.g. CAND-2048" /></div></FormSection><FormSection index="02" label="INTERVIEW DETAILS"><div className="field-grid"><Field label="Interview title" name="title" placeholder="e.g. Senior Product Designer" required /><Field label="Expected duration" name="duration" placeholder="45 minutes" required /><Field label="Date" name="date" type="date" required /><Field label="Time" name="time" type="time" required /></div><label className="field full"><span>Context for interviewer</span><textarea name="description" placeholder="Add a short brief or question themes for the interviewer." /></label></FormSection><FormSection index="03" label="MONITORING POLICY"><p className="section-note">These signals create observable events for the interviewer. They never make an automatic hiring decision.</p><div className="checks">{checks.map((check) => <label className="check" key={check}><input type="checkbox" checked={enabled[check]} onChange={() => setEnabled({ ...enabled, [check]: !enabled[check] })} /><span className="check-box">✓</span><span>{check}</span></label>)}</div></FormSection><div className="form-actions"><a className="secondary-button" href="/">Cancel</a><button className="primary-button" type="submit" disabled={submitting}>{submitting ? "Creating…" : "Create secure invitation ↗"}</button></div>{error && <div className="error-note">{error}</div>}{created && <div className="success-note"><strong>Interview created.</strong> A secure candidate invitation is ready to send. <a href="/">Return to overview</a></div>}</form></main>;
}
function FormSection({ index, label, children }: { index: string; label: string; children: React.ReactNode }) { return <section className="form-section"><div className="section-index">{index}</div><div className="form-content"><p className="eyebrow">{label}</p>{children}</div></section>; }
function Field({ label, name, placeholder = "", type = "text", required = false }: { label: string; name: string; placeholder?: string; type?: string; required?: boolean }) { return <label className="field"><span>{label}</span><input name={name} type={type} placeholder={placeholder} required={required} /></label>; }
