"use client";
import { useEffect, useState } from "react";
type Interview = { id: string; candidate_name: string; title: string; status: string; scheduled_at: string };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export default function DashboardPage() {
  const [items, setItems] = useState<Interview[]>([]); const [error, setError] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${API}/api/v1/interviews`, { headers: { Authorization: `Bearer ${localStorage.getItem("authentiq_session") ?? ""}` } }).then((r) => { if (!r.ok) throw Error(); return r.json(); }).then(setItems).catch(() => setError(true)).finally(() => setLoading(false)); }, []);
  function logout() { fetch(`${API}/api/v1/auth/logout`, { method: "POST", headers: { Authorization: `Bearer ${localStorage.getItem("authentiq_session") ?? ""}` } }).finally(() => { localStorage.removeItem("authentiq_session"); location.href = "/login"; }); }
  return <main className="simple-page dashboard-page"><header className="dashboard-header"><div><p className="eyebrow red">AUTHENTIQ / OVERVIEW</p><h1>Workspace dashboard</h1><p className="page-intro">Live data from your interview integrity API.</p></div><div className="dashboard-actions"><a className="primary-button" href={error ? undefined : "/interviews/new"}>＋ Create interview</a><button className="secondary-button" onClick={logout}>Log out</button></div></header>{error && <div className="service-alert"><strong>Workspace service unavailable</strong><p>Start the AuthentiQ backend and sign in again to load protected workspace data.</p></div>}<div className="metrics"><div className="metric"><p>Upcoming interviews</p><strong>{loading ? "…" : items.length}</strong><small>{error ? "Unavailable while offline" : "From API"}</small></div><div className="metric"><p>Workspace status</p><strong>{error ? "Offline" : "Live"}</strong><small>{error ? "Backend not reachable" : "Connected to backend"}</small></div></div><section className="api-list"><div className="section-head"><p className="eyebrow">LIVE WORKSPACE</p><h2>Upcoming interviews</h2></div>{!error && !loading && items.length === 0 && <div className="data-state"><strong>No interviews yet.</strong><span>Create your first interview to populate the workspace.</span></div>}{items.map((item) => <a className="simple-row" href={`/reports?id=${item.id}`} key={item.id}><span className="candidate-avatar">{item.candidate_name.slice(0, 2).toUpperCase()}</span><span><strong>{item.candidate_name}</strong><small>{item.title}</small></span><time>{new Date(item.scheduled_at).toLocaleString()}</time><em>{item.status}</em></a>)}</section></main>;
}
